name: Daily RSI-SuperTrend (Discord)
on:
  schedule:
    - cron: "5 0 * * *"   # 00:05 UTC every day (after daily candle)
  workflow_dispatch:       # manual run button

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      # Pinned versions to avoid build issues on the runner
      - name: Install deps (pinned)
        run: |
          pip install "numpy==1.26.4" "pandas==2.2.2" "matplotlib==3.9.2" \
                      "yfinance==0.2.52" "ta==0.11.0" "requests>=2.31"

      - name: Show environment
        run: |
          python -V
          python -c "import sys, numpy, pandas, matplotlib; \
                     print('numpy', numpy.__version__); \
                     print('pandas', pandas.__version__); \
                     print('matplotlib', matplotlib.__version__); \
                     print('platform', sys.platform)"

      - name: Run strategy and send to Discord
        run: python adaptive_strength_rsi_supertrend_auto.py

      - name: Upload chart artifact
        uses: actions/upload-artifact@v4
        with:
          name: equity-curve
          path: equity_curve_*.png
