name: Daily RSI-SuperTrend (Discord)

on:
  schedule:
    - cron: "5 0 * * *"   # 00:05 UTC  (11:05 Sydney during AEDT)
    - cron: "5 1 * * *"   # 01:05 UTC  (11:05 Sydney during AEST)
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      # Gate: only proceed when it's 11:05 in Sydney right now
      - name: Gate by Sydney local time
        id: gate
        run: |
          echo "UTC now: $(date -u)"
          TZ=Australia/Sydney date "+Sydney now: %Y-%m-%d %H:%M:%S %Z"
          SYD_TIME=$(TZ=Australia/Sydney date +%H:%M)
          echo "Sydney clock (HH:MM): $SYD_TIME"

          if [ "$SYD_TIME" = "11:05" ]; then
            echo "run=true" >> "$GITHUB_OUTPUT"
            echo "Decision: proceed (it's 11:05 in Sydney)."
          else
            echo "run=false" >> "$GITHUB_OUTPUT"
            echo "Decision: skip (not 11:05 in Sydney)."
          fi

      - name: Check out repo
        if: steps.gate.outputs.run == 'true'
        uses: actions/checkout@v4

      - name: Set up Python
        if: steps.gate.outputs.run == 'true'
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Upgrade pip
        if: steps.gate.outputs.run == 'true'
        run: python -m pip install --upgrade pip

      - name: Install dependencies
        if: steps.gate.outputs.run == 'true'
        run: |
          pip install "numpy==1.26.4" "pandas==2.2.2" "matplotlib==3.9.2" \
                      "ta==0.11.0" "requests>=2.31"

      - name: Run script (filename has spaces!)
        if: steps.gate.outputs.run == 'true'
        run: python "RSPS THE OG"

      - name: Upload chart image
        if: steps.gate.outputs.run == 'true'
        uses: actions/upload-artifact@v4
        with:
          name: equity-curve
          path: rsi_supertrend_backtest.png










