mkdir -p .github/workflows
cat > .github/workflows/daily.yml << 'YAML'
name: Daily RSI-SuperTrend (Discord)

on:
  schedule:
    - cron: "5 0 * * *"   # 00:05 UTC daily
  workflow_dispatch: 

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: python -m pip install --upgrade pip
      - run: |
          pip install "numpy==1.26.4" "pandas==2.2.2" "matplotlib==3.9.2" \
                      "ta==0.11.0" "requests>=2.31"
      - name: Run script (filename has spaces!)
        run: python "RSPS THE OG"
      - uses: actions/upload-artifact@v4
        with:
          name: equity-curve
          path: rsi_supertrend_backtest.png
YAML







