on:
  schedule:
    - cron: "5 0 * * *"   # 00:05 UTC  (11:05 Sydney in AEDT, 10:05 in AEST)
    - cron: "5 1 * * *"   # 01:05 UTC  (12:05 Sydney in AEDT, 11:05 in AEST)
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      # Run only when it's 11:05 in Sydney right now
      - name: Gate by Sydney local time
        run: |
          SYD_TIME=$(TZ=Australia/Sydney date +%H:%M)
          echo "Sydney now: $SYD_TIME"
          if [ "$SYD_TIME" != "11:05" ]; then
            echo "Not 11:05 Sydney — skipping."
            exit 0
          fi

      - name: Check out repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install dependencies
        run: |
          pip install "numpy==1.26.4" "pandas==2.2.2" "matplotlib==3.9.2" \
                      "ta==0.11.0" "requests>=2.31"

      - name: Run script (filename has spaces!)
        run: python "RSPS THE OG"

      - name: Upload chart image
        uses: actions/upload-artifact@v4
        with:
          name: equity-curve
          path: rsi_supertrend_backtest.png








