name: Daily RSI-SuperTrend (Discord)

on:
  schedule:
    # AEDT (UTC+11): 00:05 UTC == 11:05 Sydney
    - cron: "5 0 * * *"
    # AEST (UTC+10): 01:05 UTC == 11:05 Sydney
    - cron: "5 1 * * *"
  workflow_dispatch:
    inputs:
      run_anyway:
        description: "Bypass the Sydney-time gate and run now (for testing)"
        type: boolean
        default: false

concurrency:
  group: rsi-supertrend-daily
  cancel-in-progress: false

permissions:
  contents: read

env:
  TZ: Australia/Sydney

jobs:
  run:
    # Only scheduled runs proceed; manual runs require the explicit override.
    if: github.event_name == 'schedule' || (github.event_name == 'workflow_dispatch' && inputs.run_anyway == true)
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Show trigger info
        shell: bash
        run: |
          echo "Event: ${{ github.event_name }}"
          echo "Cron:  ${{ github.event.schedule || 'n/a' }}"
          echo "UTC now: $(date -u)"
          TZ=Australia/Sydney date "+Sydney now: %Y-%m-%d %H:%M:%S %Z"

      - name: Gate by Sydney local time (11:05–12:05 window)
        id: gate
        shell: bash
        run: |
          SYD_H=$(TZ=Australia/Sydney date +%H)
          SYD_M=$(TZ=Australia/Sydney date +%M)
          echo "Sydney clock H=$SYD_H M=$SYD_M"

          # Allow manual override ONLY if run_anyway=true
          if [ "${{ github.event_name }}" = "workflow_dispatch" ] && [ "${{ inputs.run_anyway }}" = "true" ]; then
            echo "run=true" >> "$GITHUB_OUTPUT"
            echo "Decision: proceed (manual override)."
            exit 0
          fi

          # 1-hour jitter window so slight cron delays still run
          if [ "$SYD_H" = "11" ] && [ "$SYD_M" -ge 5 ]; then
            echo "run=true" >> "$GITHUB_OUTPUT"
            echo "Decision: proceed (within 11:05–12:05 Sydney window)."
          elif [ "$SYD_H" = "12" ] && [ "$SYD_M" -le 5 ]; then
            echo "run=true" >> "$GITHUB_OUTPUT"
            echo "Decision: proceed (within 11:05–12:05 Sydney window)."
          else
            echo "run=false" >> "$GITHUB_OUTPUT"
            echo "Decision: skip (outside 11:05–12:05 Sydney window)."
          fi

      - name: Check out repo
        if: steps.gate.outputs.run == 'true'
        uses: actions/checkout@v4

      - name: Verify script is present
        if: steps.gate.outputs.run == 'true'
        shell: bash
        run: |
          set -euo pipefail
          echo "Listing repo root:"
          ls -la
          test -f "RSPS THE OG" || { echo "ERROR: 'RSPS THE OG' not found at repo root"; exit 1; }

      - name: Set up Python (pip cache via requirements.txt)
        if: steps.gate.outputs.run == 'true'
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"
          cache-dependency-path: "requirements.txt"

      - name: Upgrade pip
        if: steps.gate.outputs.run == 'true'
        run: python -m pip install --upgrade pip

      - name: Install dependencies
        if: steps.gate.outputs.run == 'true'
        run: pip install -r requirements.txt

      - name: Run strategy script
        if: steps.gate.outputs.run == 'true'
        run: python "RSPS THE OG"

      - name: Upload chart image (artifact)
        if: steps.gate.outputs.run == 'true' && always()
        uses: actions/upload-artifact@v4
        with:
          name: equity-curve
          path: rsi_supertrend_backtest.png
          if-no-files-found: warn

      - name: Post results to Discord (hardcoded webhook)
        if: steps.gate.outputs.run == 'true'
        shell: bash
        env:
          HOOK: "https://canary.discord.com/api/webhooks/1425769640876965990/rJb62mNKfI5aKUeUxNHkPjZ424c3gd3qaWo6IFeY5Y1RwI_Fu_yyWqn33OY6vHm69efE"
        run: |
          set -euo pipefail
          RUN_TS="$(TZ=Australia/Sydney date '+%Y-%m-%d %H:%M %Z')"
          MSG="✅ RSI-SuperTrend run finished at ${RUN_TS}"

          if [ -f "rsi_supertrend_backtest.png" ]; then
            curl -sS -X POST \
              -F "payload_json={\"content\":\"${MSG}\",\"allowed_mentions\":{\"parse\":[]}}" \
              -F "file1=@rsi_supertrend_backtest.png" \
              "$HOOK"
          else
            curl -sS -H "Content-Type: application/json" -X POST \
              -d "{\"content\":\"${MSG} (chart not found)\",\"allowed_mentions\":{\"parse\":[]}}" \
              "$HOOK"
          fi













