name: Meme Screener Daily

on:
  schedule:
    # 00:05 UTC = 11:05 AM Australia/Sydney during DST
    - cron: '05 00 * * *'
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: meme-screener-daily
  cancel-in-progress: false

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    env:
      TZ: Australia/Sydney

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade requests pandas numpy matplotlib pyarrow fastparquet jinja2

      - name: Run screener
        run: python "ALT LEAGUE"

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: meme-screener
          path: |
            meme_screener_daily.html
            meme_screener_daily.csv
            meme_screener_table.png
            meme_rsps_backtest.png
          if-no-files-found: warn



















