name: Meme Screener Daily

on:
  schedule:
    # 00:05 UTC = 11:05 AM Australia/Sydney during DST
    - cron: '05 00 * * *'
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: meme-screener-daily
  cancel-in-progress: false

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    env:
      TZ: Australia/Sydney
      # You already created this:
      COINGECKO_API_KEY: ${{ secrets.COINGECKO_API_KEY }}
      # Slightly gentler pacing for demo tier (tune 2.0–2.5 if needed)
      CG_DELAY_S: "2.2"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          # if you prefer, you can instead: pip install -r requirements.txt
          pip install --upgrade requests pandas numpy matplotlib pyarrow fastparquet

      - name: Sanity check env (won't print your key)
        run: |
          python - << 'PY'
          import os
          print("CG key present:", bool(os.getenv("COINGECKO_API_KEY")))
          print("CG_DELAY_S =", os.getenv("CG_DELAY_S"))
          PY

      - name: Run screener
        run: python "ALT LEAGUE"

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: meme-screener
          path: |
            meme_screener_daily.html
            meme_screener_daily.csv
            meme_screener_table.png
            meme_rsps_backtest.png
          if-no-files-found: warn

















